#! /usr/bin/env ruby 

require 'optparse'
require 'socket'                # Get sockets from stdlib


server = TCPServer.open(1234)   # Socket to listen on port 2000
while true 
	Thread.start(server.accept) do |client|
		file = client.readline.chop

	 	unless File.exists?(file)
			puts "No such file exists: #{file}"
			client.close()
		end

		client.puts IO.read(file)
		client.close
	end
end	
